name: CI/CD Pipeline

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Build
      run: echo "Build step placeholder ~ no build needed yet"
      working-directory: ./projects/azure-portfolio-site

    - name: Deploy to Azure Static Web Apps
      uses: azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{secrets.AZURE_STATIC_WEBAPP_TOKEN}}
        app_location: "./projects/azure-portfolio-site/src"
        repo_token: ${{secrets.GITHUB_TOKEN}}
        action: "upload"
        output_location: ""